2
name: Deploy to Cloudflare

on:
  # Trigger on new commits pushed to main
  push:
    branches: [ main ]

  # Run automatically every hour
  schedule:
    - cron: "0 0/1 * * *"

  # Allow manual trigger from Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: deploy
